apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fqbdrmm3m-nodejs 
  janus-idp.io/tekton: fqbdrmm3m-nodejs
  backstage.io/kubernetes-id: fqbdrmm3m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fqbdrmm3m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  